CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;
CREATE TABLE USUARIO (
    ID                  INTEGER         NOT NULL    DEFAULT nextval('SEQ_USUARIO'),
    NOME                VARCHAR(250)    NOT NULL,
    EMAIL               VARCHAR(100)    NOT NULL,
    SENHA               VARCHAR(500)    NOT NULL,
    DATA_NASCIMENTO     DATE            NOT NULL,
    CRIADO_EM           TIMESTAMP       NOT NULL    DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT PK_USUARIO       PRIMARY KEY (ID),
CONSTRAINT UK_USUARIO_EMAIL UNIQUE      (EMAIL)
);